apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: aaqe1zfp8-nodejs
  janus-idp.io/tekton: aaqe1zfp8-nodejs
  backstage.io/kubernetes-id: aaqe1zfp8-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: aaqe1zfp8-nodejs
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
